name: 'taxi_again_dbt'
version: '1.0.0'

profile: 'taxi_again_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  taxi_again_dbt:
    materialized: table
    staging:
      materialized: view
